// Local UI test harness. Uses the real store with a clearly labelled fixture.
const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const {Store}=require('../src/store.cjs');
const store=new Store();let settings={corner:'top-right',quiet:false,hideOnBlur:true};const listeners=new Set();let hideCount=0;let compactCount=0;let lastReply='';
const session=store.add({provider:'UI test fixture',title:'Keyboard navigation',canReply:true},{reply:async text=>{await new Promise(r=>setTimeout(r,200));lastReply=text;store.message(session.id,'agent','Reply received by the UI test fixture.');store.update(session.id,{status:'done'});}});store.message(session.id,'agent','The checks are complete. Ready for your next instruction.');store.update(session.id,{status:'done'});
if(process.env.HUSH_TEST_APPROVALS){store.actions.get(session.id).answer=async()=>{};store.enqueueRequest(session.id,{id:'first',kind:'approval',title:'Test request one'});store.enqueueRequest(session.id,{id:'second',kind:'approval',title:'Test request two'});}
const snapshot=()=>({sessions:store.list(),saved:[],settings,bridgePath:'Local test fixture only',shortcutOk:true});const broadcast=()=>{for(const r of listeners)r.write('data: '+JSON.stringify(snapshot())+'\n\n');};store.on('change',broadcast);
http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://127.0.0.1');
  if(url.pathname==='/events'){res.writeHead(200,{'Content-Type':'text/event-stream'});listeners.add(res);res.write('data: '+JSON.stringify(snapshot())+'\n\n');req.on('close',()=>listeners.delete(res));return;}
  if(url.pathname==='/state'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({...snapshot(),hideCount,compactCount,lastReply}));}
  if(url.pathname==='/action'){let raw='';for await(const c of req)raw+=c;const {name,data}=JSON.parse(raw);try{let value;if(name==='snapshot')value=snapshot();else if(name==='seen')store.seen(data.id);else if(name==='hide')hideCount++;else if(name==='settings'){settings={...settings,...data};broadcast();}else if(name==='reply')await store.reply(data.id,data.text);else if(name==='answer')await store.answer(data.id,data.requestId,data.value);else if(name==='test-notification')hideCount++;else if(name==='panel-size')compactCount++;else throw Error('This action is unavailable in the UI test fixture.');res.end(JSON.stringify({ok:true,value}));}catch(e){res.end(JSON.stringify({ok:false,error:e.message}));}return;}
  if(url.pathname==='/shim.js'){res.setHeader('Content-Type','text/javascript');return res.end(`window.hush={call:async(name,data)=>(await fetch('/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,data})})).json(),subscribe:callback=>{const events=new EventSource('/events');events.onmessage=e=>callback(JSON.parse(e.data));return()=>events.close();}};`);}
  const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!['index.html','style.css','app.js','notice.html','notice.css','notice.js'].includes(name)){res.writeHead(404);return res.end();}let content=fs.readFileSync(path.join(__dirname,'../src/ui',name));if(name.endsWith('.html'))content=content.toString().replace("connect-src 'none'","connect-src 'self'").replace('<script src="app.js">','<script src="shim.js"></script><script src="app.js">');res.setHeader('Content-Type',name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript');res.end(content);
}).listen(43917,'127.0.0.1',()=>console.log('UI fixture http://127.0.0.1:43917'));
