const test=require('node:test');const assert=require('node:assert/strict');const {PassThrough}=require('node:stream');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {Store}=require('../src/store.cjs');const {Rpc}=require('../src/rpc.cjs');const {WindowPolicy}=require('../src/window-policy.cjs');const {createBridge}=require('../src/bridge.cjs');const {HushClient}=require('../bin/client.cjs');
test('replies stay scoped and a failed delivery is not recorded as sent',async()=>{const s=new Store();let received='';const a=s.add({provider:'A',title:'A',canReply:true},{reply:async t=>{received=t;}});const b=s.add({provider:'B',title:'B',canReply:true},{reply:async()=>{throw Error('disconnected');}});await s.reply(a.id,'hello');assert.equal(received,'hello');await assert.rejects(s.reply(b.id,'keep draft'),/disconnected/);assert.equal(b.messages.length,0);assert.equal(b.sending,false);assert.equal(a.messages[0].text,'hello');});
test('stale approval cannot resolve a newer request',async()=>{const s=new Store();let called=false;const a=s.add({provider:'A',title:'A'},{answer:async()=>{called=true;}});s.update(a.id,{status:'waiting',request:{id:'new'}});await assert.rejects(s.answer(a.id,'old','accept'),/already been resolved/);assert.equal(called,false);await s.answer(a.id,'new','decline');assert.equal(a.request,null);});
test('concurrent approvals remain visible in order',async()=>{const store=new Store();const s=store.add({provider:'A',title:'A'},{answer:async()=>{}});store.enqueueRequest(s.id,{id:'first'});store.enqueueRequest(s.id,{id:'second'});assert.equal(s.request.id,'first');await store.answer(s.id,'first','accept');assert.equal(s.request.id,'second');assert.equal(s.status,'waiting');await store.answer(s.id,'second','decline');assert.equal(s.request,null);});
test('busy and disconnected agents do not accept duplicate replies',async()=>{const s=new Store();const a=s.add({provider:'A',title:'A',canReply:true},{reply:async()=>{}});s.update(a.id,{status:'working'});await assert.rejects(s.reply(a.id,'hi'),/still working/);s.update(a.id,{status:'offline'});await assert.rejects(s.reply(a.id,'hi'),/source app/);});
test('quiet and idle have zero overlay, notifications never focus',async()=>{const events=[];let visible=false;const panel={isMinimized:()=>!visible,restore:()=>{visible=true;},minimize:()=>{visible=false;},isVisible:()=>visible,show:()=>{visible=true;events.push('show');},focus:()=>events.push('focus'),hide:()=>{visible=false;events.push('hide');}};const notice={showInactive:()=>events.push('inactive'),hide:()=>events.push('notice-hide')};const p=new WindowPolicy({panel,notice,duration:10,cooldown:100});p.attention();p.attention();assert.deepEqual(events,['inactive']);await new Promise(r=>setTimeout(r,20));assert.equal(events.at(-1),'notice-hide');p.setQuiet(true);p.lastNotice=0;p.attention();assert.equal(events.filter(x=>x==='inactive').length,1);p.open();assert.equal(events.at(-1),'focus');p.hide();assert.equal(visible,false);p.close();});
test('RPC handles fragmented JSON and rejects outstanding calls on disconnect',async()=>{const input=new PassThrough(),output=new PassThrough(),rpc=new Rpc(input,output);let sent='';output.on('data',c=>sent+=c);const request=rpc.call('hello');const id=JSON.parse(sent).id;input.write(`{"id":${id},"res`);input.write('ult":{"ok":true}}\n');assert.deepEqual(await request,{ok:true});const pending=rpc.call('next');rpc.close();await assert.rejects(pending,/disconnected/);});
test('authenticated bridge delivers replies, requires acknowledgement and isolates sessions',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hush-test-'));const store=new Store();const bridge=await createBridge(store,dir);try{const a=await new HushClient(bridge.filename).connect('Tool A','A');const b=await new HushClient(bridge.filename).connect('Tool B','B');await a.event('done','Result');assert.equal(store.get(a.id).messages[0].text,'Result');await store.reply(a.id,'follow up');const replies=await a.replies();assert.equal(replies[0].text,'follow up');assert.equal((await b.replies()).length,0);assert.equal((await a.replies()).length,1);await a.ack(replies[0].id);assert.equal((await a.replies()).length,0);const config=JSON.parse(fs.readFileSync(bridge.filename));let r=await fetch(config.url+'/sessions',{method:'POST',body:'{}'});assert.equal(r.status,401);r=await fetch(config.url+'/sessions',{method:'POST',headers:{Authorization:`Bearer ${config.token}`,Origin:'https://evil.example'},body:'{}'});assert.equal(r.status,401);const original=a.key;a.key=b.key;await assert.rejects(a.replies(),/Unknown session/);a.key=original;}finally{bridge.close();await store.close();fs.rmSync(dir,{recursive:true,force:true});}});
