const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');const {Rpc}=require('./rpc.cjs');
// The Cursor Agent CLI ships its own Node and entry script side by side in a versioned
// directory, but installs that directory somewhere different on each platform, so look in
// every place its installers use rather than assuming one. The newest version wins.
function cursorRuntime(){
  const home=require('node:os').homedir();
  const roots=process.platform==='win32'
    ? [path.join(process.env.LOCALAPPDATA||'','cursor-agent','versions')]
    : [path.join(process.env.XDG_DATA_HOME||path.join(home,'.local','share'),'cursor-agent','versions'),
       path.join(home,'.cursor-agent','versions'),
       path.join(home,'.local','share','cursor-agent','versions')];
  const node=process.platform==='win32'?'node.exe':'node';
  const found=roots.flatMap(root=>{
    try{return fs.readdirSync(root).sort().reverse().map(name=>path.join(root,name));}catch{return [];}
  }).find(dir=>fs.existsSync(path.join(dir,node))&&fs.existsSync(path.join(dir,'index.js')));
  if(!found)throw Error('Install Cursor Agent CLI first.');
  return {binary:path.join(found,node),script:path.join(found,'index.js')};
}
class Cursor {
 constructor(store){this.store=store;this.sessions=new Map();this.requests=new Map();this.acceptances=new Map();}
 async ready(){if(!this.starting)this.starting=(async()=>{const r=cursorRuntime();this.child=spawn(r.binary,[r.script,'acp'],{windowsHide:true,stdio:['pipe','pipe','pipe']});const child=this.child;const rpc=this.rpc=new Rpc(child.stdout,child.stdin);const send=rpc.send.bind(rpc);rpc.send=m=>send({jsonrpc:'2.0',...m});this.child.stderr.resume();this.child.on('error',e=>rpc.close(e));this.child.on('exit',()=>rpc.close());rpc.on('event',m=>this.event(m));rpc.on('closed',error=>{child.kill();this.starting=null;this.requests.clear();for(const a of this.acceptances.values())a.reject(error);this.acceptances.clear();for(const id of this.sessions.values())if(this.store.sessions.has(id))this.store.update(id,{status:'offline',canReply:false,request:null,requests:[]});});return rpc.call('initialize',{protocolVersion:1,clientCapabilities:{},clientInfo:{name:'hush',version:'0.4.0'}});})().catch(e=>{this.child?.kill();this.starting=null;throw e;});return this.starting;}
 event(m){const p=m.params||{},id=this.sessions.get(p.sessionId);if(m.id!==undefined){if(id&&m.method==='session/request_permission'){this.acceptances.get(p.sessionId)?.resolve();const key=String(m.id);this.requests.set(key,{id:m.id,options:p.options});this.store.enqueueRequest(id,{id:key,kind:'approval',title:p.toolCall?.title||'Cursor needs permission'});}else this.rpc.send({id:m.id,error:{code:-32601,message:'This request needs the original Cursor client.'}});return;}if(!id||m.method!=='session/update')return;const u=p.update;if(['agent_message_chunk','user_message_chunk'].includes(u?.sessionUpdate)&&u.content?.type==='text'){if(u.sessionUpdate==='agent_message_chunk')this.acceptances.get(p.sessionId)?.resolve();const s=this.store.get(id);if(u.sessionUpdate==='user_message_chunk'&&s.canReply)return;const role=u.sessionUpdate==='agent_message_chunk'?'agent':'you';const last=s.messages.at(-1);if(last?.role===role&&last.streaming){last.text+=u.content.text;this.store.update(id,{});}else{this.store.message(id,role,u.content.text);s.messages.at(-1).streaming=true;}}}
 async list(){await this.ready();const result=await this.rpc.call('session/list',{});return (result.sessions||[]).map(s=>({provider:'cursor',sourceId:s.sessionId,title:s.title||'Cursor conversation',cwd:s.cwd||'',updatedAt:Date.parse(s.updatedAt)||0}));}
 async connect({cwd,title,resumeId}){await this.ready();const s=this.store.add({provider:'Cursor',title:title||'Cursor conversation',cwd,sourceId:resumeId||'',canReply:false});if(resumeId)this.sessions.set(resumeId,s.id);
 try{const result=await this.rpc.call(resumeId?'session/load':'session/new',{cwd,mcpServers:[],...(resumeId?{sessionId:resumeId}:{})});s.sourceId=resumeId||result.sessionId;this.sessions.set(s.sourceId,s.id);const models=(result.models?.availableModels||[]).map(m=>({id:m.modelId,name:m.name}));this.store.actions.set(s.id,{reply:async(text,options={})=>{if(options.model&&options.model!==s.model){if(!models.some(m=>m.id===options.model))throw Error('Choose an available Cursor model.');await this.rpc.call('session/set_model',{sessionId:s.sourceId,modelId:options.model});this.store.update(s.id,{model:options.model});}const prompt=[{type:'text',text},...(options.attachments||[]).map(a=>({type:'image',mimeType:a.mimeType,data:fs.readFileSync(a.path).toString('base64')}))];this.store.update(s.id,{status:'working'});const accepted=new Promise((resolve,reject)=>this.acceptances.set(s.sourceId,{resolve,reject}));this.rpc.call('session/prompt',{sessionId:s.sourceId,prompt},600000).then(()=>{this.acceptances.get(s.sourceId)?.resolve();s.messages.forEach(m=>delete m.streaming);this.store.update(s.id,{status:'done'});}).catch(e=>{this.acceptances.get(s.sourceId)?.reject(e);this.store.message(s.id,'system',e.message);this.store.update(s.id,{status:'error'});});try{await accepted;}finally{this.acceptances.delete(s.sourceId);}},answer:async(id,value)=>{const req=this.requests.get(id);if(!req)throw Error('Request expired.');const option=req.options.find(o=>o.kind===(value==='accept'?'allow_once':'reject_once'));this.rpc.send({id:req.id,result:{outcome:option?{outcome:'selected',optionId:option.optionId}:{outcome:'cancelled'}}});this.requests.delete(id);},dispose:()=>this.sessions.delete(s.sourceId)});this.store.update(s.id,{canReply:true,images:true,models,model:result.models?.currentModelId||''});return s;}catch(e){this.sessions.delete(resumeId);await this.store.remove(s.id);throw e;}}
 close(){this.rpc?.close();this.child?.kill();}
}
module.exports={Cursor,cursorRuntime};
